### ISSUE TITLE
Issue: it doesn't work in creative

### ISSUE THREAD

**Issue by SepSol** [maruohon/itemscroller#29]

**Comment by maruohon** [comment]
The creative *player inventory* is a weird mess and the slots work totally differently from any normal inventories. There is specific support for shift + dragging from the hotbar, but that's it. Even that needed a bunch of extra code already. Implementing everything else would need almost all of the code to be duplicated and adjusted for the creative inventory, and afaik it wouldn't even be that often useful. I guess maybe stuff like the shift + dropping might be useful to add still.

Currently you can work around this and for example shift + drop all items of a type from the creative player inventory by opening any container and doing it in that GUI, because there the slots are normal simple nice & clean slots.

**Comment by SepSol** [comment]
Thanks for letting me know then :)
