### ISSUE TITLE
Disconnect from server

### ISSUE THREAD

**Issue by Elastik55** [maruohon/itemscroller#40]
Hi! 
I've used Item Scroller for a few months now and I love it. After installing it (and some other mods) I started getting disconnected from the server randomly. The message I'm getting in my client is _Internal Exception: java.io.IOEexception: An existing connection was forcibly closed by the remote host_ 
I'm an admin of the server so I've checked the server console and there it just says that player disconnected. 

After a few months of this I decided to try and find the issue. I tried a clean client, and no disconnects after 1 hour. 
Then I tried a clean instance and reinstalled all the mods that I had on the old one. Disconnected within 5 minutes. 
Then I started trying each mod loaded on its own and that's when I was able to conclude that Item Scroller was the issue. 
I also tried loading the game with only MaLib enabled and that worked fine. 

The disconnect happens more, but not exclusively, when I'm moving quickly(IE flying elytra) or using a nether portal. 

My version of minecraft: 1.15.2
Fabric version: 0.8.9+build.203
Fabric API: fabric-api-0.14.0+build.317-1.15
MaLib: malilib-fabric-1.15.2-0.10.0-dev.21+arne.3
Item Scroller: itemscroller-fabric-1.15.2-0.15.0-dev.20200616.032713

Running all this through MultiMC if that makes a difference
No one else on the server claims to have these issues.

**Comment by maruohon** [comment]
Item Scroller should be doing absolutely nothing when you are just flying with an elytra. The only plausible reason for Item Scroller causing disconnects would be while you are using for example some of the crafting features, which can spam very large amounts of slot click packets.

If it happens when you are not even inside an inventory screen, then I very much doubt that IS could be the cause, it might just be random coincidence. My first guess would be due to internet connection issues, and while flying around you are receiving lots of somewhat large chunk packets from the server.

**Comment by Elastik55** [comment]
I'm not having issues in any other games. When running ping google.com-t in cmd i get between 8 and 15ms over an hours test. 
and with ping google.com-n I get 0% loss
Maybe I should try pinging the server ip instead.

**Comment by maruohon** [comment]
It's hard to say anything with this little information, plus I'm not experienced in network stuff in any case. But ping packets are also very small and infrequent compared to the chunk data packets for example. It might be that there are some network issues somewhere along the path from your computer to the server, at least when there is more data to transfer, like loading lots of chunks.

**Comment by Elastik55** [comment]
Yeah it happened on a clean client now. Apologies for taking your time!
