### ISSUE TITLE
[bug] DropAllMatching doesnt work in creative

### ISSUE THREAD

**Issue by ghost** [maruohon/itemscroller#45]
To my testing, the dropp all matching doesnt work in creative [neither with the standart hotkeys or with the hotkey set to another key]. This affects version for 1.16.3 (maybe also others but i havent tested that].
In survival and adventuremode it works just fine though.

**Comment by maruohon** [comment]
Actually pretty much none of the features work in the creative player inventory.
This is because the creative player inventory slots work entirely differently from normal slots, and they would need a different implementation of pretty much all of the code for each feature. Currently there is special support for just click + dragging so that you can use that to clear the hotbar in creative mode.

I want to pretty much entirely rewrite the mod (code-wise) at some point, so it *might be* possible that during that rewrite there might be a way to support the creative inventory, but I can't say for sure before I start on that at some point. In the current codebase it's not feasible, since like I mentioned I would need to copy paste and adapt all of the code to make a separate code path for the creative inventory alone.

**Comment by ghost** [comment]
Well ok. Still thank you very much
