### ISSUE TITLE
How to favorite a villager's trades?

### ISSUE THREAD

**Issue by James103** [maruohon/itemscroller#47]
There is the `villagerTradeFavorites` hotkey, which trades "everything possible with all the favorited trades of the current villager". However, the favorited trades list appears to start off empty, and I don't know how I can add trades to my favorited trades list so that they get executed when pressing the `villagerTradeFavorites` hotkey.

What hotkeys do I need to press and what do I need to do in order to favorite a villager's trades?

Minecraft: 1.16.4
Fabric Loader: 0.10.8
Item Scroller: 0.15.0-dev.20201103.183933
MaLiLib: 0.10.0-dev.21+arne.2

**Comment by maruohon** [comment]
The trade favorites and related functionality currently only exists in the 1.12.x and 1.13.2 versions. It was removed in the 1.14 port due to the villagers and trading related stuff being rewritten in vanilla, and at least in the first 1.14 versions it seemed mostly redundant due to the new trade refresh cooldowns. But I forgot to remove the hotkey...

However I do intend to add it back, but I need to rewrite the code for the 1.14+ villager GUIs.

**Comment by James103** [comment]
Closing, as the requested feature is implemented in recent versions.
