### ISSUE TITLE
Shift + Left Click (Hold) and Hovering through Tinker's Inventories

### ISSUE THREAD

**Issue by everseeking** [maruohon/itemscroller#5]
First discovered in FTB Unstable pack on on these versions:

- itemscroller-1.10.2-0.5.2
- itemscroller-1.10.2-0.6.0 (Saw this update, issue found on this as well)

Along with this Tinker's version:
- TConstruct-1.10-2.3.3a

When using the "Shift + Left Click" functionality from itemscroller, when holding left click and moving the cursor through a Tinker's inventory (crafting table as well as smeltry), items may or may not be moved into the player's inventory, but more importantly, items from the player's inventory may also be moved back into the Tinker's inventory.

Example: Using this functionality to empty a Tinker's crafting table of ingredients, I've had my tools be pulled into the crafting grid when I was just removing stone from the crafting table.

I would guess that Tinker's is doing something unique with its inventory (custom or utilizing Forge). This behavior does not happen with vanilla crafting tables. I have also removed any other inventory sorting or enhancement mods (such as inventory tweaks) to make sure it wasn't some kind of conflict - I'm fairly certain my testing has isolated it down to your mod interacting with Tinker's Construct.

If you need anything else just let me know.

**Comment by maruohon** [comment]
Yep Tinkers is using some sort of wrappers/modules for their slots, so me trying to get the slot directly by the mouse cursor position the way vanilla also does it doesn't work.

I now switched into using reflection to call the normally private method getSlotAtPosition() from GuiContainer to get the slot, and since Tinkers is overriding some of the methods that are used by that method's call chain, it will now work correctly.

So this will be fixed in version 0.6.1. I'll try to fix/improve one other thing before I upload the release, but I also have to eat something before I get to that stuff...

**Comment by everseeking** [comment]
Awesome, thanks for the quick fix and response! Looking forward to the next release and I'll let you know if I come across anything else. Thank you again.
