### ISSUE TITLE
Mod hasn't compat with EasierVillagersTrading

### ISSUE THREAD

**Issue by crosspedestrian** [maruohon/itemscroller#55]
When Itemscroller exists at the same time, EasierVillagersTrading by gbl don't take effect although his mod can be loaded. Trading is shown as vanilla.

First I went to gbl for help however the pity is that he can't do much about that.  Can you solve the problem？Thanks.
https://github.com/gbl/EasierVillagerTrading/issues/21

Game Verison: 1.16.5
a) When I load MaLiLib with any one of above, EasierVillagersTrading works normal.
b) When I load all mods except Item Scroller, EasierVillagersTrading works normal.
c) When I load MaLiLib and Item Scroller with any one of others, EasierVillagersTrading can't work but it is loaded (appear in the modmenu mod).

**Comment by maruohon** [comment]
Looks like the incompatibility comes from Item Scroller's handling of the custom re-ordered client-side trade list. There might be some changes that could be made to do things differently to allow Easier Villager Trading to still also work. But I'm not sure if it would even work correctly due to the trade list re-ordering, it might end up using the wrong indices if you have any favorited trades with Item Scroller and thus the list being in a different order on the server side.

Also from the looks of it, Item Scroller is only missing the feature of clicking a trade to immediately trade only once. Is this the feature you want to use? Trading everything possible with a given trade also exists in Item Scroller, by right clicking on the trades. Or if you don't want to use Item Scroller's trading features (right click to fully trade a given trade, or the favoriting and trading all favorites at once feature) then you can also turn off the trade features, which allows Easier Villager Trading to work. You can turn these off at `I + C` -> Toggles -> `enableVillagerTradeFeatures`.
