### ISSUE TITLE
Shift + Click an item out of the inventory while having an AE2 Terminal open also drops the first item in your inventory

### ISSUE THREAD

**Issue by Xiaminou** [maruohon/itemscroller#8]
so I was trying that Shift + Click an item out of the inventory, and I happen to try it while browsing an AE2 Terminal.

Here it is: https://youtu.be/GZ4StWW73Cw

Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/maruohon/itemscroller/files/657764/list.txt)

**Comment by maruohon** [comment]
This happened whenever the item you were dropping was also in the ME system and visible on the screen, because all the AE2 slots for some reason claim to be slotNumber 0, so then the faked slot click happened for the first slot in the player inventory instead, which actually is slotNumber 0...

But in any case, this is now fixed in 0.9.0 because of the change I made that the shift + dropping now only drops items from the same inventory that you pick them up from (and thus checks for the inventory reference).

**Comment by Xiaminou** [comment]
Good to know, thanks.
